version: 2
updates:
  - package-ecosystem: "npm" # Ecosystem for frontend
    directory: "./frontend" # Localização dos manifests do frontend
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip" # Ecosystem for backend (Python)
    directory: "./backend" # Localização dos manifests do backend
    schedule:
      interval: "weekly"
