services:
  api:
    container_name: backend
    image: socialnet-backend:development
    build:
      platforms:
        - linux/amd64
        - linux/arm64
      context: ./backend
      dockerfile: Dockerfile.development
    ports:
      - 5000:5000
    volumes:
      - ./backend/src/backend:/api/backend

# TO-DO: add frontend container