services:
  backend:
    container_name: backend
    image: socialnet-backend:development
    build:
      platforms:
        - linux/amd64
        - linux/arm64
      context: ./backend
      dockerfile: Dockerfile.development
    ports:
      - 5000:5000
    volumes:
      - ./backend/src/backend:/api/backend
      - ./backend/.env:/api/.env

  frontend:
    container_name: frontend
    image: socialnet-frontend:development
    build:
      platforms:
        - linux/amd64
        - linux/arm64
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
