FROM python:3.12-slim

RUN adduser api

COPY --chown=api:api src/backend /api/backend

COPY --chown=api:api pyproject.toml poetry.lock .env.development /api/

RUN pip install poetry

USER api

WORKDIR /api

RUN poetry install

EXPOSE 5000

CMD ["poetry", "run", "uvicorn", "backend.main:app", "--host", "0.0.0.0", "--port", "5000"]