@startuml "deployment"

title Deployment Diagram

node "Application Server" {
  artifact "Frontend" as frontend
  artifact "Backend" as backend
  artifact "Auth" as auth
}

node "Database Server" {
  database "Database" as db
}

node "Client" {
  artifact "Web Browser" as browser
}

browser --> frontend

frontend --> auth : HTTPS
auth --> frontend : HTTPS

frontend --> backend : HTTPS
backend --> frontend : HTTPS
backend --> auth : HTTPS
auth --> backend : HTTPS

backend --> db : SQL

@enduml
