name: Build Backend on PR

on:
  pull_request:
    branches: [main]

jobs:
  build-backend:
    runs-on: [self-hosted]
    defaults:
      run:
        working-directory: ./backend

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: deadsnakes/action@v3.1.0
        with:
          python-version: "3.12"

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - name: Install Poetry
        run: python -m pip install poetry toml

      - name: Install dependencies
        run: poetry install

      - name: Test with pytest
        run: poetry run pytest

      - name: Get pyproject version
        run: |
          version=$(python -c "import toml; print(toml.load('pyproject.toml')['tool']['poetry']['version'])")
          echo "DOCKER_VERSION=$version" >> $GITHUB_ENV

      - name: Build Docker image
        run: docker build -f Dockerfile.production -t socialnet-backend:$DOCKER_VERSION .
