name: Build Backend on PR

on:
  pull_request:
    branches: [main]

jobs:
  build-backend:
    runs-on: [self-hosted]

    defaults:
      run:
        working-directory: ./backend

    permissions:
      contents: read
      issues: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: setup python
        uses: deadsnakes/action@v3.1.0
        with:
          python-version: "3.11"

      - name: Install Poetry
        run: pip install poetry toml

      - name: Install dependencies
        run: poetry install

      - name: Test with pytest
        run: |
          poetry run pytest --cov=backend tests >> result.log
          echo "## Backend Test Coverage" > comment.md
          poetry run coverage report --format markdown >> comment.md
        env:
          REDIS_HOST: "127.0.0.1"
          TEST_USER_EMAIL: ${{ secrets.TEST_USER_EMAIL }}
          TEST_USER_PASSWORD: ${{ secrets.TEST_USER_PASSWORD }}

      - name: Post coverage comment on PR
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            $(cat comment.md)

      - name: Get pyproject version
        run: |
          version=$(python3 -c "import toml; print(toml.load('pyproject.toml')['tool']['poetry']['version'])")
          echo "DOCKER_VERSION=$version" >> $GITHUB_ENV

      - name: Build Docker image
        run: docker build -f Dockerfile.production -t socialnet-backend:$DOCKER_VERSION .

      - name: Tag Latest Version
        run: docker image tag socialnet-backend:$DOCKER_VERSION socialnet-backend:latest

      - name: Deploy Backend Container
        run: VERSION=$DOCKER_VERSION docker compose -f ~/stack/backend/docker-compose.yaml up -d