name: Build Backend on PR

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: [self-hosted]
    defaults:
      run:
        working-directory: ./backend

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          architecture: "arm64"
          cache: 'pip'

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - name: Install Poetry
        run: python -m pip install poetry

      - name: Install dependencies
        run: poetry install --dev

      - name: Test with pytest
        run: poetry run pytest

      - name: Get pyproject version
        run: |
          version=$(python -c "import toml; print(toml.load('pyproject.toml')['tool']['poetry']['version'])")
          echo "VERSION=$version" >> $GITHUB_ENV

      - name: Build Docker image
        run: docker build -f Dockerfile.production -t socialnet-backend:$VERSION .
