name: Build Backend on PR

on:
  workflow_dispatch:
  pull_request:
    branches: [main]
    paths:
      - backend/**

jobs:
  build-backend:
    runs-on: [self-hosted]

    defaults:
      run:
        working-directory: ./backend

    permissions:
      contents: read
      issues: write
      pull-requests: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Generate .env
        run: |
          echo $BASE64_ENCODED_DOTENV | base64 -d > .env
        env:
            BASE64_ENCODED_DOTENV: ${{ secrets.BASE64_ENCODED_DOTENV }}

      - name: setup python
        uses: deadsnakes/action@v3.1.0
        with:
          python-version: "3.11"

      - name: Install Poetry
        run: pip install poetry toml

      - name: Install dependencies
        run: poetry install

      - name: Test with pytest
        run: |
          poetry run pytest --cov=backend tests >> result.log
          echo "## Backend Test Coverage" > comment.md
          poetry run coverage report --format markdown >> comment.md

      - name: Find Coverage Comment on PR
        uses: peter-evans/find-comment@v3
        id: fc
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: Backend Test Coverage
    
      - name: Post Coverage Comment on PR
        if: steps.fc.outputs.comment-id == ''
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body-path: ./backend/comment.md
          
      - name: Update Coverage Comment on PR
        if: ${{ github.event_name == 'pull_request' }}
        uses: peter-evans/create-or-update-comment@v4
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          body-path: ./backend/comment.md
          edit-mode: replace
  
      - name: Build Docker image
        run: docker build -f Dockerfile.production -t socialnet-backend:development .
  
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.22.0
        with:
          image-ref: 'socialnet-backend:development'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'