name: Build Frontend on PR

on:
  pull_request:
    branches: [ main ]
    paths:
      - frontend/**

jobs:
  build-frontend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.9.0'

    - name: Install dependencies
      run: npm install
      working-directory: ./frontend

    - name: Build
      env:
        NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
        NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
      run: npm run build
      working-directory: ./frontend

    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
        projectKey: "tomasoliveira21_desofs2024_M1B_3"
        organization: "tomasoliveira21"
        scannerMode: "CLI"
        configMode: "manual"
        cliOptions: >
          -Dsonar.projectBaseDir=./frontend
          -Dsonar.sources=.
          -Dsonar.host.url=https://sonarcloud.io

  zap_scan:
    runs-on: ubuntu-latest
    needs: build-frontend

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Start ZAP
      run: docker run -u zap -p 8080:8080 -d owasp/zap2docker-stable zap-x.sh -daemon -port 8080 -config api.key=${{ secrets.ZAP_API_KEY }}

    - name: Wait for ZAP to start
      run: sleep 30

    - name: Run ZAP Scan
      run: |
        docker run -t owasp/zap2docker-stable zap-cli quick-scan --self-contained --start-options '-config api.key=${{ secrets.ZAP_API_KEY }}' --api-key ${{ secrets.ZAP_API_KEY }} http://localhost:3000
        docker run -t owasp/zap2docker-stable zap-cli report -o zap_report.html -f html
      env:
        ZAP_API_KEY: ${{ secrets.ZAP_API_KEY }}

    - name: Upload ZAP Report
      uses: actions/upload-artifact@v2
      with:
        name: ZAP Report
        path: zap_report.html
