{% extends "buildspec_base.yml" %}

{% block deploy_commands %}
      - |
        if [ -z "$NO_MIGRATE" ]; then
          aws ecs register-task-definition --cli-input-json file://deployment/production/prod-socialnet-backend-migration.json
          aws ecs run-task --cluster production --task-definition prod-socialnet-backend-migration
        fi

      - aws ecs register-task-definition --cli-input-json file://deployment/production/prod-socialnet-backend-web.json
      - aws ecs register-task-definition --cli-input-json file://deployment/production/prod-socialnet-backend-grpc.json
      - aws ecs register-task-definition --cli-input-json file://deployment/production/prod-socialnet-backend-worker.json
      - aws ecs register-task-definition --cli-input-json file://deployment/production/prod-socialnet-backend-scheduler.json
      - aws ecs register-task-definition --cli-input-json file://deployment/production/prod-socialnet-backend-admin.json

      - |
        if [ -z "$ADMIN_ONLY" ]; then
          aws ecs update-service --cluster production --service socialnet-backend-web --task-definition prod-socialnet-backend-web
          aws ecs update-service --cluster production --service socialnet-backend-grpc --task-definition prod-socialnet-backend-grpc
          aws ecs update-service --cluster production --service socialnet-backend-worker --task-definition prod-socialnet-backend-worker
          aws ecs update-service --cluster production --service socialnet-backend-scheduler --task-definition prod-socialnet-backend-scheduler --deployment-configuration maximumPercent=100,minimumHealthyPercent=0
        fi

      - aws ecs update-service --cluster admin --service prod-socialnet-backend-admin --task-definition prod-socialnet-backend-admin --deployment-configuration maximumPercent=100,minimumHealthyPercent=0
{% endblock %}
